apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
      - name: cicd-demo
        image: image-registry.openshift-image-registry.svc:5000/akshayjunejaa-dev/cicd-demo:latest
        ports:
        - containerPort: 8080
